package com.iprism.swenhealth.utils

object Constants {


//    const val BASE_URL = "https://caremanagers.in/ecmanagers/trade_marketing/ws/"
//    const val IMAGES_URL = "https://caremanagers.in/ecmanagers/"

    //Test Server
    const val BASE_URL = "https://iprismsmartsolutions.com/ecmanagers/trade_marketing/ws/"
    const val IMAGES_URL = "https://iprismsmartsolutions.com/ecmanagers/"

//    const val LOGIN_ENDPOINT = "login"
//    const val RESEND_OTP_ENDPOINT = "resend_otp"
//    const val HOME_PAGE_ENDPOINT = "home_page"
//    const val ALL_CATEGORIES_ENDPOINT = "all_categories"
//    const val ALL_SYMPTOMS_SPECIALITIES_ENDPOINT = "all_symptoms_specialisation"
//    const val MEDICAL_DEGREES_ENDPOINT = "all_medical_degrees"
//    const val USER_DROP_DOWNS_ENDPOINT = "user_dropdowns"
//    const val ADD_DOCTOR_ENDPOINT = "add_doctor"
//    const val DOCTORS_ENDPOINT = "doctors"
//    const val HOSPITAL_DOCTORS_ENDPOINT = "hospital_doctors"
//    const val ADD_LEAD_ENDPOINT = "add_lead"
//    const val LEADS_ENDPOINT = "leads"
//    const val HEALTH_ADVISOR_CATEGORIES = "all_health_advisor_categories"
//    const val HEALTH_ADVISOR_SUB_CATEGORIES_ENDPOINT = "all_health_advisor_sub_categories"
//    const val HEALTH_CLUB_TASKS_ENDPOINT = "all_health_club_tasks"
//    const val ADD_HEALTH_ADVISOR_ENDPOINT = "add_health_advisor"
//    const val INBOUND_CATEGORIES_ENDPOINT = "all_inbound_marketing_categories"
//    const val INBOUND_SUB_CATEGORIES_ENDPOINT = "all_inbound_marketing_sub_categories"
//    const val INBOUND_SUB_SUB_CATEGORIES_ENDPOINT = "all_inbound_marketing_sub_sub_categories"
//    const val HEALTH_ADVISOR_TASKS_ENDPOINT = "all_health_advisor_tasks"
//    const val ADD_INBOUND_MEMBER_ENDPOINT = "add_inbound_marketing_member"
//    const val TOTAL_LEADS_ENDPOINT = "total_leads"
//    const val TOTAL_HEALTH_ADVISORS_ENDPOINT = "total_health_advisors"
//    const val HOSPITAL_HODS_ENDPOINT = "hospital_hods"
//    const val TEAM_CONNECT_ENDPOINT = "team_connect"
//    const val DAILY_REPORTS_ENDPOINT = "daily_reports"
//    const val TOTAL_INBOUND_MARKETERS_ENDPOINT = "total_inbound_marketers"
//    const val TARIFFS_ENDPOINT = "tariffs"
//    const val SURGICAL_PACKAGES_ENDPOINT = "surgical_packages"
//    const val PROFILE_ENDPOINT = "profile"
//    const val WHITEBOARD_FEEDBACK_ENDPOINT = "whiteboard"
//    const val EVENTS_ENDPOINT = "events"
//    const val TODO_LIST_ENDPOINT = "todo_list"
//    const val TASK_AND_PERFORMANCE_ENDPOINT = "task_performance"
//    const val CONTENT_PAGES_ENDPOINT = "content_pages"
//    const val HOSPITAL_FACILITIES_ENDPOINT = "facilities"
//    const val HOSPITAL_TIEUPS_ENDPOINT = "tieups"
//    const val CONTACT_US_ENDPOINT = "contact_us"
//    const val HEALTH_MEDIA_ENDPOINT = "health_media"
//    const val DIGITAL_PROMOS_ENDPOINT = "digital_promos"
//    const val REQUEST_AMBULANCE_ENDPOINT = "request_an_ambulance"
//    const val REFER_ADMISSION_ENDPOINT = "refer_admission"
//    const val REFER_DIAGNOSTIC_ENDPOINT = "refer_diagnostics"
//    const val SEND_INSURANCE_PRE_AUTH_ENDPOINT = "send_insurance_pre_auth"
//    const val HOSPITAL_ASSISTANCE_ENDPOINT = "request_refer"
//    const val TESTIMONIAL_VIDEOS_ENDPOINT = "all_videos"
//    const val REWARDS_ENDPOINT = "rewards"
//    const val NOTIFICATIONS_ENDPOINT = "notifications"

}